spring:
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: namiq
    password: 12345

  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: postgres
    password: passsword
