spring:
  application:
    name: ms-book
  profiles:
    active:
      -docker
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

user-service:
  url: http://localhost:8081