spring:
  application:
    name: ms-book

  datasource:
    url: jdbc:postgresql://books-postgres:5432/books_db
    username: postgres
    password: passsword

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: namiq
    password: 12345

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

user-service:
  url: http://ms-user:8081