spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: namiq
    password: 12345
    listener:
      simple:
        default-requeue-rejected: false
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000

  datasource:
    url: jdbc:postgresql://users-postgres:5432/users_db
    username: postgres
    password: passsword